language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
before_install:
  - git submodule init
  - git submodule update
mono:
  - latest
os:
  - linux
  - osx
osx_image: xcode7.3
script:
  - dotnet restore && dotnet build **/project.json
