language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
mono:
  - latest
os:
  - linux
  - osx
osx_image: xcode7.3
install:
  - nuget restore sdk/sdk.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
before_script:
 - chmod +x Travis/installSubmodule.sh
script:
  - Travis/installSubmodule.sh
  - xbuild /p:Configuration=Release sdk/sdk.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/Test/bin/Release/Test.dll
#  - dotnet restore && dotnet build **/project.json
