language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
mono:
- latest
os:
- linux
osx_image: xcode7.3
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore sdk/sdk.sln
  - nuget restore Test/Test.sln
  - nuget install NUnit.ConsoleRunner
before_script:
  - chmod +x Travis/installSubmodule.sh
script:
  - Travis/installSubmodule.sh
  - Travis/build.sh
  - Travis/initConfig.sh
after_script:
  - nunit-console Test/Test/bin/Release/Tests.dll
