language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
mono:
- latest
os:
- linux
osx_image: xcode7.3
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore sdk/sdk.sln
  - nuget restore Test/Test.sln
  - nuget install NUnit.ConsoleRunner
#  - nuget install OpenCover -version 4.6.519 -outputdirectory .\packages
#  - nuget install ReportGenerator -version 2.5.1 -outputdirectory .\packages
before_script:
  - chmod +x Travis/installSubmodule.sh
  - chmod +x Travis/build.sh
  - chmod +x Travis/initConfig.sh
#  - chmod +x Travis/generateCodeCoverageReport.sh
script:
  - Travis/installSubmodule.sh
  - Travis/build.sh
  - Travis/initConfig.sh
#  - Travis/generateCodeCoverageReport.sh
