language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
mono:
- latest
os:
- linux
osx_image: xcode7.3
install:
- nuget restore sdk/sdk.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
before_script:
- chmod +x Travis/installSubmodule.sh
script:
- Travis/installSubmodule.sh
- nuget restore Test/Test.sln
- xbuild /p:Configuration=Release sdk/sdk.sln
- xbuild /p:Configuration=Release Test/Test.sln
- openssl aes-256-cbc -K $encrypted_89fb597d004e_key -iv $encrypted_89fb597d004e_iv
  -in Config.json.enc -out Config.json -d
- mkdir -p Test/Test/bin/Release/appdata/
- mv Config.json Test/Test/bin/Release/appdata/Config.json
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Test/Test/bin/Release/Test.dll
