language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
mono:
- latest
os:
- linux
osx_image: xcode7.3
install:
- nuget restore sdk/sdk.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
before_script:
- chmod +x Travis/installSubmodule.sh
script:
- Travis/installSubmodule.sh
- Travis/build.sh
- Travis/initConfig.sh
