language: csharp
solution: sdk/sdk.sln
dist: trusty
sudo: required
git:
  submodules: false
mono:
- latest
os:
- linux
install:
- nuget restore sdk/sdk.sln
- nuget restore Test/Test.sln
- nuget install NUnit.ConsoleRunner
before_script:
- chmod a+x Travis/installSubmodule.sh
- chmod a+x Travis/build.sh
- chmod a+x Travis/coverage.sh
- chmod a+x Travis/coveralls.sh
script:
- Travis/installSubmodule.sh
- Travis/build.sh
- Travis/coverage.sh
- Travis/coveralls.sh
after_success:
- coveralls
env:
  global:
    secure: mvVXTl3GjEqSeuOAiVhiQABhQNg/J+U2J8gQO6R9Vu6VCmedJwjzYbOQ03092s8HEjK/eiNnd19XORQ7ZJzNihoIE5MO5Ya2LkMxcu3xjQbIDVYVePmjtybNpPZdZKTp+r+o0ULqAnp0xQv/BEF51sgZX1WGgPfwrbWRd0+r45GjetIumlEhtC5Qn01nDfiJ55B+J4YrvKZGssgw6gXRFrhXNEGgX3NT5ll6x9o+j8jHrRlR7/5hydbaBny+Bq4+fJEtWNuJxAVDODQBZQDSNqYdGG/UejJ4FO5+QFcJ/n5r/HvCGN1bXZMzBYnEvHIs/kOH/0a1fXaI+LDHITlQV0T65/+++bKS9xv36mxVLKk+Cj06KTWm8zCBUYd7/5axs9/leLNuM6NNwjL5WqFb6qMes+5eP+kygfA7qX91tx/50S46dDmHFWBNFXMriTEaacu1gmwYSQlpPTLfoxUBNtKl0NPU9MckTyCuVL3wNgUbw67IzIN8JpF+8rFJD7G2MyTooWNDs24pd5cTDcd8dWLUJS9z4g+MvBZJzOtCVTb9hN5lNA2KfO/CAaGcC3VQ7/Eo5zljLPBVoX/AGWXScdkMkOnXxyL/0YafnoLSl+2UHvovw12xRhdusqGi0csFk0k1EwluCagI/iga6vAR5Fo/w+XrEJt+RhG3rfLaGrk=
